name: data-chat
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  #- pytorch=2.1.*
  #- pytorch-cuda=11.8
  - cuda-nvcc=11.8
  - cuda-libraries-dev=11.8
  - cudatoolkit=11.8
  #- pytorch=2.2.2
  #- pytorch-cuda=12.1
  - pip:
      - -r requirements_dev.txt
      - -r requirements.txt